version: "3.7"

services:
  database:
    image: mysql:8.0
    platform: linux/amd64
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=codetest
      - MYSQL_USER=codetest
      - MYSQL_PASSWORD=swordfish
    ports:
      - "3306:3306"
    restart: always

  example-python:
    image: example-python
    build: images/example-python
    command: ["./example.py"]
    volumes:
      - ./data:/data

  loaddata:
    image: loaddata
    build: images/loaddata
    command: ["python","./loadData.py"]
    volumes:
      - ./data:/data
      
  outputdata:
    image: outputdata
    build: images/outputdata
    command: ["python","./outputData.py"]
    volumes:
      - ./data:/data      
